piece_symbol = { "P" | "R" | "N" | "B" | "Q" | "K" }
promotion_piece = { "R" | "Q" | "B" | "N" }
column = { 'a' .. 'h' }
row = { '1' .. '8' }

target_field = { column ~ row }
origin_field = { target_field | column | row }

pawn_move = { origin_field ~ "x" ~ target_field ~ "=" ~ promotion_piece | origin_field ~ "x" ~ target_field | target_field ~ "=" ~ promotion_piece | target_field }

castling = { "O-O-O" | "0-0-0" | "O-O" | "0-0" }

piece_move = { origin_field ~ target_field | "x" ~ target_field | origin_field ~ "x" ~ target_field | target_field }
piece_move_full = { piece_symbol ~ piece_move }

turn = { castling | piece_move_full | pawn_move }
